req_entry:
    location_address: Test Address
    location_latitude_g: 1.1
    location_longitude_g: 2.2
    location_zoom_g: 1
    blog_id: 1
    locator_beacon: 1
    _type: entry

req_blog:
    location_address: Test Address
    location_latitude_g: 1.1
    location_longitude_g: 2.2
    location_zoom_g: 1
    blog_id: 1
    locator_beacon: 1
    _type: blog

req_author:
    location_address: Test Address
    location_latitude_g: 1.1
    location_longitude_g: 2.2
    location_zoom_g: 1
    blog_id: 1
    locator_beacon: 1
    _type: author
